// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Notebook.DataAccess.DataContext;

namespace Notebook.DataAccess.Migrations
{
    [DbContext(typeof(NotebookContext))]
    [Migration("20190622220751_1")]
    partial class _1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Notebook.Entities.Entities.Folder", b =>
                {
                    b.Property<string>("ID")
                        .HasMaxLength(8);

                    b.Property<DateTime>("CreateDate");

                    b.Property<string>("Explanation");

                    b.Property<string>("Name");

                    b.Property<string>("OwnerID");

                    b.Property<int>("Visible");

                    b.HasKey("ID");

                    b.HasIndex("OwnerID");

                    b.ToTable("Folder");
                });

            modelBuilder.Entity("Notebook.Entities.Entities.FolderNote", b =>
                {
                    b.Property<string>("FolderID");

                    b.Property<string>("NoteID");

                    b.Property<DateTime>("CreateDate");

                    b.Property<string>("ID")
                        .IsRequired()
                        .HasMaxLength(8);

                    b.HasKey("FolderID", "NoteID");

                    b.HasAlternateKey("ID");

                    b.HasIndex("NoteID");

                    b.ToTable("FolderNote");
                });

            modelBuilder.Entity("Notebook.Entities.Entities.Follow", b =>
                {
                    b.Property<string>("FollowerID");

                    b.Property<string>("FollowingID");

                    b.Property<string>("ID")
                        .IsRequired()
                        .HasMaxLength(8);

                    b.Property<bool>("Notification");

                    b.HasKey("FollowerID", "FollowingID");

                    b.HasAlternateKey("ID");

                    b.HasIndex("FollowingID");

                    b.ToTable("Follow");
                });

            modelBuilder.Entity("Notebook.Entities.Entities.Group", b =>
                {
                    b.Property<string>("ID")
                        .HasMaxLength(8);

                    b.Property<DateTime>("CreateDate");

                    b.Property<string>("Explanation");

                    b.Property<bool>("IsRequiredApproval");

                    b.Property<string>("Name");

                    b.Property<string>("OwnerID");

                    b.Property<int>("Visible");

                    b.HasKey("ID");

                    b.HasIndex("OwnerID");

                    b.ToTable("Group");
                });

            modelBuilder.Entity("Notebook.Entities.Entities.GroupFolder", b =>
                {
                    b.Property<string>("GroupID");

                    b.Property<string>("FolderID");

                    b.Property<DateTime>("CreateDate");

                    b.Property<string>("ID")
                        .IsRequired()
                        .HasMaxLength(8);

                    b.HasKey("GroupID", "FolderID");

                    b.HasAlternateKey("ID");

                    b.HasIndex("FolderID");

                    b.ToTable("GroupFolder");
                });

            modelBuilder.Entity("Notebook.Entities.Entities.GroupNote", b =>
                {
                    b.Property<string>("GroupID");

                    b.Property<string>("NoteID");

                    b.Property<DateTime>("CreateDate");

                    b.Property<string>("ID")
                        .IsRequired()
                        .HasMaxLength(8);

                    b.HasKey("GroupID", "NoteID");

                    b.HasAlternateKey("ID");

                    b.HasIndex("NoteID");

                    b.ToTable("GroupNote");
                });

            modelBuilder.Entity("Notebook.Entities.Entities.Log", b =>
                {
                    b.Property<string>("ID")
                        .HasMaxLength(8);

                    b.Property<DateTime>("DateTime");

                    b.Property<string>("Detail");

                    b.HasKey("ID");

                    b.ToTable("Log");
                });

            modelBuilder.Entity("Notebook.Entities.Entities.Note", b =>
                {
                    b.Property<string>("ID")
                        .HasMaxLength(8);

                    b.Property<string>("Content");

                    b.Property<DateTime>("CreateDate");

                    b.Property<string>("Explanation");

                    b.Property<string>("OwnerID");

                    b.Property<int>("ReadCount");

                    b.Property<string>("Tags");

                    b.Property<string>("Title");

                    b.Property<DateTime>("UpdateDate");

                    b.Property<int>("Visible");

                    b.HasKey("ID");

                    b.HasIndex("OwnerID");

                    b.ToTable("Note");
                });

            modelBuilder.Entity("Notebook.Entities.Entities.NotebookSettings", b =>
                {
                    b.Property<string>("ID")
                        .HasMaxLength(8);

                    b.HasKey("ID");

                    b.ToTable("NotebookSettings");
                });

            modelBuilder.Entity("Notebook.Entities.Entities.Role", b =>
                {
                    b.Property<string>("ID")
                        .HasMaxLength(8);

                    b.Property<string>("Authorization");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            ID = "863a12r5",
                            Authorization = "ADD_ROLE,EDIT_ROLE,NEW_ROLE,ADD_USER,EDIT_USER,NEW_USER,USER_ROLE",
                            Name = "admin"
                        });
                });

            modelBuilder.Entity("Notebook.Entities.Entities.User", b =>
                {
                    b.Property<string>("ID")
                        .HasMaxLength(8);

                    b.Property<bool>("Approve");

                    b.Property<string>("Avatar");

                    b.Property<DateTime>("CreateDate");

                    b.Property<string>("Email");

                    b.Property<string>("Info");

                    b.Property<DateTime>("LastActiveDate");

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.Property<string>("RoleID");

                    b.Property<string>("Username");

                    b.HasKey("ID");

                    b.HasIndex("RoleID");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            ID = "23m454h5",
                            Approve = true,
                            Avatar = "/notebook/images/avatar.png",
                            CreateDate = new DateTime(2019, 6, 23, 1, 7, 51, 464, DateTimeKind.Local).AddTicks(1211),
                            Email = "muammer.hafizogluu@gmail.com",
                            LastActiveDate = new DateTime(2019, 6, 23, 1, 7, 51, 465, DateTimeKind.Local).AddTicks(1281),
                            Name = "Muammer Hafızoğlu",
                            Password = "D3CE20FCCBE7D116ECD0",
                            Username = "muammer.hafizoglu"
                        });
                });

            modelBuilder.Entity("Notebook.Entities.Entities.UserFolder", b =>
                {
                    b.Property<string>("UserID");

                    b.Property<string>("FolderID");

                    b.Property<DateTime>("CreateDate");

                    b.Property<string>("ID")
                        .IsRequired()
                        .HasMaxLength(8);

                    b.Property<int>("MemberType");

                    b.Property<bool>("Notification");

                    b.HasKey("UserID", "FolderID");

                    b.HasAlternateKey("ID");

                    b.HasIndex("FolderID");

                    b.ToTable("UserFolder");
                });

            modelBuilder.Entity("Notebook.Entities.Entities.UserGroup", b =>
                {
                    b.Property<string>("UserID");

                    b.Property<string>("GroupID");

                    b.Property<DateTime>("CreateDate");

                    b.Property<string>("ID")
                        .IsRequired()
                        .HasMaxLength(8);

                    b.Property<int>("MemberType");

                    b.Property<bool>("Notification");

                    b.HasKey("UserID", "GroupID");

                    b.HasAlternateKey("ID");

                    b.HasIndex("GroupID");

                    b.ToTable("UserGroup");
                });

            modelBuilder.Entity("Notebook.Entities.Entities.UserNote", b =>
                {
                    b.Property<string>("UserID");

                    b.Property<string>("NoteID");

                    b.Property<DateTime>("CreateDate");

                    b.Property<string>("ID")
                        .IsRequired()
                        .HasMaxLength(8);

                    b.Property<int>("Member");

                    b.HasKey("UserID", "NoteID");

                    b.HasAlternateKey("ID");

                    b.HasIndex("NoteID");

                    b.ToTable("UserNote");
                });

            modelBuilder.Entity("Notebook.Entities.Entities.UserSettings", b =>
                {
                    b.Property<string>("ID")
                        .HasMaxLength(8);

                    b.Property<string>("UserID");

                    b.HasKey("ID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("Notebook.Entities.Entities.Folder", b =>
                {
                    b.HasOne("Notebook.Entities.Entities.User", "Owner")
                        .WithMany("Folders")
                        .HasForeignKey("OwnerID");
                });

            modelBuilder.Entity("Notebook.Entities.Entities.FolderNote", b =>
                {
                    b.HasOne("Notebook.Entities.Entities.Folder", "Folder")
                        .WithMany("Notes")
                        .HasForeignKey("FolderID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Notebook.Entities.Entities.Note", "Note")
                        .WithMany("Folders")
                        .HasForeignKey("NoteID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Notebook.Entities.Entities.Follow", b =>
                {
                    b.HasOne("Notebook.Entities.Entities.User", "Follower")
                        .WithMany("Followers")
                        .HasForeignKey("FollowerID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Notebook.Entities.Entities.User", "Following")
                        .WithMany("Following")
                        .HasForeignKey("FollowingID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Notebook.Entities.Entities.Group", b =>
                {
                    b.HasOne("Notebook.Entities.Entities.User", "Owner")
                        .WithMany("Groups")
                        .HasForeignKey("OwnerID");
                });

            modelBuilder.Entity("Notebook.Entities.Entities.GroupFolder", b =>
                {
                    b.HasOne("Notebook.Entities.Entities.Folder", "Folder")
                        .WithMany("Groups")
                        .HasForeignKey("FolderID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Notebook.Entities.Entities.Group", "Group")
                        .WithMany("Folders")
                        .HasForeignKey("GroupID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Notebook.Entities.Entities.GroupNote", b =>
                {
                    b.HasOne("Notebook.Entities.Entities.Group", "Group")
                        .WithMany("Notes")
                        .HasForeignKey("GroupID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Notebook.Entities.Entities.Note", "Note")
                        .WithMany("Groups")
                        .HasForeignKey("NoteID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Notebook.Entities.Entities.Note", b =>
                {
                    b.HasOne("Notebook.Entities.Entities.User", "Owner")
                        .WithMany("Notes")
                        .HasForeignKey("OwnerID");
                });

            modelBuilder.Entity("Notebook.Entities.Entities.User", b =>
                {
                    b.HasOne("Notebook.Entities.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleID");
                });

            modelBuilder.Entity("Notebook.Entities.Entities.UserFolder", b =>
                {
                    b.HasOne("Notebook.Entities.Entities.Folder", "Folder")
                        .WithMany("Users")
                        .HasForeignKey("FolderID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Notebook.Entities.Entities.User", "User")
                        .WithMany("SucscribedFolders")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Notebook.Entities.Entities.UserGroup", b =>
                {
                    b.HasOne("Notebook.Entities.Entities.Group", "Group")
                        .WithMany("Users")
                        .HasForeignKey("GroupID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Notebook.Entities.Entities.User", "User")
                        .WithMany("SucscribedGroups")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Notebook.Entities.Entities.UserNote", b =>
                {
                    b.HasOne("Notebook.Entities.Entities.Note", "Note")
                        .WithMany("Users")
                        .HasForeignKey("NoteID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Notebook.Entities.Entities.User", "User")
                        .WithMany("SucscribedNotes")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Notebook.Entities.Entities.UserSettings", b =>
                {
                    b.HasOne("Notebook.Entities.Entities.User", "User")
                        .WithOne("Settings")
                        .HasForeignKey("Notebook.Entities.Entities.UserSettings", "UserID");
                });
#pragma warning restore 612, 618
        }
    }
}
